### ISSUE TITLE
Need instructions on how to install git version 

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/ngmaster#16]
Specifically

%
git clone ...
pip install --user ngmaster/
%

The trailing slash is **critical**.

And tell them it will be in `$HOME/.local/bin` !

**Comment by andersgs** [comment]
By default, yes, the binary will be in `$HOME/.local/bin`, but it can be specified to something else at install:

    --install-option <options>  Extra arguments to be supplied to the setup.py install command (use like --install-option
                              ="--install-scripts=/usr/local/bin"). Use multiple --install-option options to pass multiple
                              options to setup.py install. If you are using an option with a directory path, be sure to use
                              absolute path.

There is more info in response to #15 on a way that does not need to `git clone` first. 

I'll update the README.

**Comment by andersgs** [comment]
These are now addressed in pull request #18.
