### ISSUE TITLE
Database update Error

### ISSUE THREAD

**Issue by DrReemaSingh** [MDU-PHL/ngmaster#28]
Hello,
I am trying to update the NGMASTER db files and getting following error:-

`ngmaster --updatedb
WARNING: seccomp requested but not enabled, seccomp library is missing or too old
Welcome to NGMATER 0.5.1
DB updated on 2018-02-09
WARNING: Updating DB will overwrite existing DB files.
Continue? [y/n]: y
Updating DB files ...
Unable to download/process URL:'http://www.ng-mast.net/sql/fasta.asp?allele=POR'
`
Could you please let me know- how can I solve this and update the underlying database?
I look forward to the reply!

Thanks,
Reema,

**Comment by kwongj** [comment]
Not sure, but you can just download the database manually from here: http://www.ng-mast.net/sql/fasta.asp?allele=POR and save in the `db` directory.

**Comment by tseemann** [comment]
@DrReemaSingh  you can use this hack to get the new POR file. As @kwongj said you'll need to put it in your ngmaster `db` folder.

```
curl 'http://www.ng-mast.net/sql/fasta.asp?allele=POR' | tr " " "\n"  | gep -A 1 '^&gt;POR' | sed 's/&gt;/>/' > POR.tfa
```

**Comment by tseemann** [comment]
@DrReemaSingh 

Updating worked fine on version 0.5.5 for me

```
Updating DB files ... 
/home/linuxbrew/.linuxbrew/Cellar/ngmaster/0.5.5/libexec/lib/python3.7/site-packages/ngmaster-0.5.5-py3.7.egg/ngmaster/db/POR.tfa ... Done.
/home/linuxbrew/.linuxbrew/Cellar/ngmaster/0.5.5/libexec/lib/python3.7/site-packages/ngmaster-0.5.5-py3.7.egg/ngmaster/db/TBPB.tfa ... Done.
/home/linuxbrew/.linuxbrew/Cellar/ngmaster/0.5.5/libexec/lib/python3.7/site-packages/ngmaster-0.5.5-py3.7.egg/ngmaster/db/ng_mast.txt ... Done.
```

**Comment by DrReemaSingh** [comment]
@tseemann :- NGMATER 0.5.1 I am using right now. I am downloding it from:

[https://singularity-hub.org/collections/579/usage](url)

And these are the command that I used to download NGMASTER

`singularity pull shub://phgenomics-singularity/ngmaster`
`singularity pull --name ngmaster.img shub://phgenomics-singularity/ngmaster`

Welcome to NGMATER 0.5.1
DB updated on 2018-02-09

Still downloading the 0.5.1 VERSION.

**Comment by DrReemaSingh** [comment]
> @DrReemaSingh you can use this hack to get the new POR file. As @kwongj said you'll need to put it in your ngmaster `db` folder.
> 
> ```
> curl 'http://www.ng-mast.net/sql/fasta.asp?allele=POR' | tr " " "\n"  | grep -A 1 '^&gt;POR' | sed 's/&gt;/>/' > POR.tfa
> ```
> I also not you are using version 0.5.1 when the current is 0.5.5

@tseemann : Thank you for sharing this command. I see - porB and  tbpB, I can download from here. 
But how could i GET THE "ng_mast.txt" ?
