### ISSUE TITLE
updatedb unable to update database

### ISSUE THREAD

**Issue by DrReemaSingh** [MDU-PHL/ngmaster#29]
Hi,

I have reinstalled the latest version of NgMASTER on my machine. But I am still not able to update the database. Please see below:

`$ ngmaster --version`
`ngmaster 0.5.5`

`ngmaster --updatedb`
`WARNING: Updating DB will overwrite existing DB files.`
`Continue? [y/n]: y`
`Updating DB files ...`
`Unable to download/process URL:'http://www.ng-mast.net/sql/fasta.asp?allele=POR'`

NGMASTER installed successfully without showing any warnings or errors. Could you please help me out with this?
I look forward to the reply!

PS: https://github.com/MDU-PHL/ngmaster/issues/28

**Comment by andersgs** [comment]
@DrReemaSingh sorry for the delay in responding to this one. I have not been able to reproduce the error. But, I just made a new release with the latest DB. Please let me know if this is still an issue and I'll re-open.
