### ISSUE TITLE
Errors when running make command in isPcrSrc directory

### ISSUE THREAD

**Issue by jayminz** [MDU-PHL/ngmaster#32]
I downloaded the isPcr33.zip from the link you provided and tried to install this program by following README file in the isPcrSrc directory. Everything has been set up well according to the instruction, except when I run the command line "make" and they are showing some errors. I have no idea how to fix it as I don't much familiar with the code. The errors were shown as below:

> cd lib && make
> make[1]: Entering directory '/home/chanwit/isPcr33/isPcrSrc/lib'
> gcc -O  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_ -DJK_WARN -Wall -Werror -I../inc -I../../inc -I../../../inc -I../../../../inc  -c aliType.c
> aliType.c:5:19: error: ‘rcsid’ defined but not used [-Werror=unused-const-variable=]
>  static char const rcsid[] = "$Id: aliType.c,v 1.4 2003/05/06 07:33:41 kate Exp $";
>                    ^~~~~
> cc1: all warnings being treated as errors
> ../inc/common.mk:40: recipe for target 'aliType.o' failed
> make[1]: *** [aliType.o] Error 1
> make[1]: Leaving directory '/home/chanwit/isPcr33/isPcrSrc/lib'
> makefile:2: recipe for target 'all' failed
> make: *** [all] Error 2
> 

It has some trouble with the lib makefile. For your information, I have already installed biopython, python 3.6 and ngmaster (via the pip command). So when I run ngmaster, it showed the text "ERROR: Check isPcr is installed correctly and in $PATH". 

Thank you for your kind help.

**Comment by andersgs** [comment]
hi @jayminz can you tell me a little more about your system?

You can install isPCR with conda now: 

`conda install -c bioconda ispcr`

My goal is to have `ngmaster` up on conda soon.

Cheers. A.

**Comment by jayminz** [comment]
hi @andersgs my operating system is Ubuntu 18.04 LTS. After installing as you suggested, the ngmaster program is currently working. I appreciate for your help.

**Comment by tseemann** [comment]
That's great news @jayminz
